SELECT count(*) FROM car_1_MODEL_LIST AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id JOIN car_1_COUNTRIES AS T3 ON T2.Country  =  T3.CountryId WHERE T3.CountryName  =  'usa';;
SELECT name FROM employee_hire_evaluation_shop WHERE shop_id NOT IN (SELECT shop_id FROM employee_hire_evaluation_hiring);
SELECT T2.feature_type_name FROM real_estate_properties_Other_Available_Features AS T1 JOIN real_estate_properties_Ref_Feature_Types AS T2 ON T1.feature_type_code  =  T2.feature_type_code WHERE T1.feature_name  =  "AirCon";
SELECT count(*) FROM flight_2_AIRPORTS;
SELECT count(DISTINCT RESULT) FROM battle_death_battle;
SELECT section_description FROM student_transcripts_tracking_Sections WHERE section_name  =  'h';
SELECT Earnings FROM poker_player_poker_player ORDER BY Earnings DESC;
SELECT t2.name FROM employee_hire_evaluation_hiring AS t1 JOIN employee_hire_evaluation_shop AS t2 ON t1.shop_id  =  t2.shop_id GROUP BY t1.shop_id ORDER BY count(*) DESC LIMIT 1;
SELECT country_code FROM wta_1_players GROUP BY country_code ORDER BY count(*) DESC LIMIT 1;
SELECT professional_id ,  role_code ,  email_address FROM dog_kennels_Professionals EXCEPT SELECT T1.professional_id ,  T1.role_code ,  T1.email_address FROM dog_kennels_Professionals AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.professional_id  =  T2.professional_id;
SELECT T1.first_name ,  T2.name FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id WHERE T1.state  =  'Virginia';
SELECT name ,  capacity FROM concert_singer_stadium ORDER BY average DESC LIMIT 1;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline GROUP BY T1.Airline HAVING count(*)  <  200;
SELECT LOCATION ,  name FROM concert_singer_stadium WHERE capacity BETWEEN 5000 AND 10000;
select count(*) FROM car_1_countries as t1 JOIN car_1_car_makers as t2 on t1.countryid  =  t2.country group by t1.countryid having count(*)  >  2;
SELECT T1.paragraph_id ,   T1.paragraph_text FROM cre_Doc_Template_Mgt_Paragraphs AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.document_id  =  T2.document_id WHERE T2.Document_Name  =  'Welcome to NY';
SELECT winner_name FROM wta_1_matches WHERE tourney_name  =  'Australian Open' ORDER BY winner_rank_points DESC LIMIT 1;
SELECT count(*) FROM tvshow_Cartoon WHERE Written_by = "Joseph Kuhr";;
SELECT avg(Earnings) FROM poker_player_poker_player;
SELECT T1.Continent FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode GROUP BY T1.Continent ORDER BY COUNT(*) DESC LIMIT 1;
SELECT Name FROM course_teach_teacher WHERE Teacher_id NOT IN (SELECT Teacher_id FROM course_teach_course_arrange);
SELECT count(*) FROM museum_visit_visitor WHERE id NOT IN (SELECT t2.visitor_id FROM museum_visit_museum AS t1 JOIN museum_visit_visit AS t2 ON t1.Museum_ID  =  t2.Museum_ID WHERE t1.open_year  >  2010);
SELECT Model FROM car_1_CAR_NAMES GROUP BY Model ORDER BY count(*) DESC LIMIT 1;;
SELECT property_name FROM real_estate_properties_Properties WHERE property_type_code  =  "House" UNION SELECT property_name FROM real_estate_properties_Properties WHERE property_type_code  =  "Apartment" AND room_count  >  1;
SELECT count(*) FROM student_transcripts_tracking_Courses;
SELECT template_type_code ,  count(*) FROM cre_Doc_Template_Mgt_Templates GROUP BY template_type_code;
SELECT COUNT(*) FROM orchestra_orchestra WHERE Major_Record_Format  =  "CD" OR Major_Record_Format  =  "DVD";
SELECT major ,  age FROM pets_1_student WHERE stuid NOT IN (SELECT T1.stuid FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat');
SELECT T1.first_name ,  T1.middle_name ,  T1.last_name ,  T1.student_id FROM student_transcripts_tracking_Students AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.student_id  =  T2.student_id GROUP BY T1.student_id HAVING count(*)  =  2;
select citizenship FROM singer_singer group by citizenship order by count(*) desc limit 1;
SELECT T1.first_name ,  T2.name FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id;
SELECT email_address ,  cell_number ,  home_phone FROM dog_kennels_professionals;
SELECT count(*) FROM battle_death_ship WHERE disposition_of_ship  =  'Captured';
select production_code ,  channel FROM tvshow_cartoon order by original_air_date desc limit 1;
SELECT count(*) FROM dog_kennels_Owners WHERE owner_id NOT IN ( SELECT owner_id FROM dog_kennels_Dogs );
SELECT T1.owner_id ,  T1.zip_code FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id JOIN dog_kennels_Treatments AS T3 ON T2.dog_id  =  T3.dog_id GROUP BY T1.owner_id ORDER BY sum(T3.cost_of_treatment) DESC LIMIT 1;
SELECT Final_Table_Made ,  Best_Finish FROM poker_player_poker_player;
SELECT vote_id ,  phone_number ,  state FROM voter_1_votes;
SELECT Population ,  LifeExpectancy FROM world_1_country WHERE Name  =  "Brazil";
SELECT count(*) ,  District FROM world_1_city WHERE Population  >  (SELECT avg(Population) FROM world_1_city) GROUP BY District;
SELECT avg(Attendance) FROM orchestra_SHOW;
SELECT name ,  LOCATION ,  district FROM employee_hire_evaluation_shop ORDER BY number_products DESC;
SELECT document_id FROM cre_Doc_Template_Mgt_Paragraphs GROUP BY document_id HAVING count(*) BETWEEN 1 AND 2;
SELECT T2.Name FROM course_teach_course_arrange AS T1 JOIN course_teach_teacher AS T2 ON T1.Teacher_ID  =  T2.Teacher_ID GROUP BY T2.Name HAVING COUNT(*)  >=  2;
SELECT count(*) ,  LOCATION FROM employee_hire_evaluation_shop GROUP BY LOCATION;
SELECT template_id FROM cre_Doc_Template_Mgt_Documents GROUP BY template_id HAVING count(*)  >  1;
SELECT Citizenship ,  max(Net_Worth_Millions) FROM singer_singer GROUP BY Citizenship;
SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" AND T2.IsOfficial  =  "T" INTERSECT SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "French" AND T2.IsOfficial  =  "T";
SELECT document_id FROM cre_Doc_Template_Mgt_Paragraphs GROUP BY document_id ORDER BY count(*) ASC LIMIT 1;
SELECT avg(age) FROM dog_kennels_Dogs;
SELECT template_id ,  count(*) FROM cre_Doc_Template_Mgt_Documents GROUP BY template_id;
SELECT DISTINCT T2.Name FROM world_1_country AS T1 JOIN world_1_city AS T2 ON T2.CountryCode  =  T1.Code WHERE T1.Continent  =  'Europe' AND T1.Name NOT IN (SELECT T3.Name FROM world_1_country AS T3 JOIN world_1_countrylanguage AS T4 ON T3.Code  =  T4.CountryCode WHERE T4.IsOfficial  =  'T' AND T4.Language  =  'English');
SELECT T1.course_name ,  T1.course_id FROM student_transcripts_tracking_Courses AS T1 JOIN student_transcripts_tracking_Sections AS T2 ON T1.course_id  =  T2.course_id GROUP BY T1.course_id HAVING count(*)  <=  2;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.SourceAirport  =  "AHD";
SELECT Population ,  Region FROM world_1_country WHERE Name  =  "Angola";
SELECT COUNT(*) FROM car_1_CARS_DATA WHERE Cylinders  >  6;;
SELECT * FROM employee_hire_evaluation_hiring;
SELECT count(*) FROM museum_visit_museum WHERE open_year  >  2013 OR open_year  <  2008;
select avg(capacity) ,  max(capacity) FROM concert_singer_stadium;
SELECT T1.fname ,  T1.sex FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid GROUP BY T1.stuid HAVING count(*)  >  1;
SELECT DISTINCT T1.Name FROM singer_singer AS T1 JOIN singer_song AS T2 ON T1.Singer_ID  =  T2.Singer_ID WHERE T2.Sales  >  300000;
SELECT DISTINCT T1.date_arrived ,  T1.date_departed FROM dog_kennels_Dogs AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.dog_id  =  T2.dog_id;
SELECT country_code FROM wta_1_players GROUP BY country_code HAVING count(*)  >  50;
SELECT T1.Model FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T2.Cylinders  =  4 ORDER BY T2.horsepower DESC LIMIT 1;;
SELECT count(*) FROM network_1_Highschooler;
SELECT contestant_name FROM voter_1_contestants WHERE contestant_name != 'Jessie Alloway';
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.SourceAirport  =  "APG" INTERSECT SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.SourceAirport  =  "CVO";
SELECT avg(LifeExpectancy) FROM world_1_country WHERE Continent  =  "Africa" AND GovernmentForm  =  "Republic";
SELECT T1.degree_program_id ,  T1.degree_summary_name FROM student_transcripts_tracking_Degree_Programs AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.degree_program_id  =  T2.degree_program_id GROUP BY T1.degree_program_id ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM pets_1_pets WHERE weight  >  10;
SELECT T2.name ,  T2.location FROM concert_singer_concert AS T1 JOIN concert_singer_stadium AS T2 ON T1.stadium_id  =  T2.stadium_id WHERE T1.Year  =  2014 INTERSECT SELECT T2.name ,  T2.location FROM concert_singer_concert AS T1 JOIN concert_singer_stadium AS T2 ON T1.stadium_id  =  T2.stadium_id WHERE T1.Year  =  2015;
SELECT count(DISTINCT department_id) FROM student_transcripts_tracking_Degree_Programs;
select cell_mobile_number FROM student_transcripts_tracking_students where first_name  =  'timmothy' and last_name  =  'ward';
SELECT T1.contestant_number , T1.contestant_name FROM voter_1_contestants AS T1 JOIN voter_1_votes AS T2 ON T1.contestant_number  =  T2.contestant_number GROUP BY T1.contestant_number ORDER BY count(*) ASC LIMIT 1;
SELECT transcript_date ,  other_details FROM student_transcripts_tracking_Transcripts ORDER BY transcript_date ASC LIMIT 1;
SELECT T1.series_name FROM tvshow_TV_Channel AS T1 JOIN tvshow_TV_series AS T2 ON T1.id = T2.Channel WHERE T2.Episode = "A Love of a Lifetime";;
SELECT Hometown FROM course_teach_teacher GROUP BY Hometown HAVING COUNT(*)  >=  2;
SELECT Age ,  Hometown FROM course_teach_teacher;
select avg(age) FROM pets_1_student where stuid not in (select stuid FROM pets_1_has_pet);
SELECT AirportName FROM flight_2_AIRPORTS WHERE City = "Aberdeen";
SELECT charge_type ,  charge_amount FROM dog_kennels_Charges;
SELECT max(area_code) ,  min(area_code) FROM voter_1_area_code_state;
SELECT role_code ,  street ,  city ,  state FROM dog_kennels_professionals WHERE city LIKE '%West%';
SELECT T2.name FROM network_1_Likes AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id ORDER BY count(*) DESC LIMIT 1;
SELECT T1.template_type_code ,  count(*) FROM cre_Doc_Template_Mgt_Templates AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.template_id  =  T2.template_id GROUP BY T1.template_type_code;
SELECT T1.owner_id ,  T1.last_name FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id JOIN dog_kennels_Treatments AS T3 ON T2.dog_id  =  T3.dog_id GROUP BY T1.owner_id ORDER BY count(*) DESC LIMIT 1;
SELECT first_name FROM student_transcripts_tracking_Students WHERE current_address_id != permanent_address_id;
SELECT T1.City FROM flight_2_AIRPORTS AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.AirportCode  =  T2.SourceAirport GROUP BY T1.City ORDER BY count(*) DESC LIMIT 1;
SELECT Airline FROM flight_2_AIRLINES WHERE Abbreviation  =  "UAL";
SELECT template_type_code FROM cre_Doc_Template_Mgt_Templates GROUP BY template_type_code HAVING count(*)  <  3;
SELECT song_name FROM concert_singer_singer WHERE age  >  (SELECT avg(age) FROM concert_singer_singer);
SELECT DISTINCT breed_code ,  size_code FROM dog_kennels_dogs;
SELECT section_name FROM student_transcripts_tracking_Sections ORDER BY section_name DESC;
SELECT Name FROM orchestra_conductor ORDER BY Age ASC;
SELECT avg(grade) FROM network_1_Highschooler WHERE id IN (SELECT T1.student_id FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id);
SELECT max(SHARE) , min(SHARE) FROM tvshow_TV_series;;
select distinct t3.name FROM world_1_country as t1 JOIN world_1_countrylanguage as t2 on t1.code  =  t2.countrycode JOIN world_1_city as t3 on t1.code  =  t3.countrycode where t2.isofficial  =  't' and t2.language  =  'chinese' and t1.continent  =  "asia";
SELECT sum(ranking_points) ,  T1.first_name FROM wta_1_players AS T1 JOIN wta_1_rankings AS T2 ON T1.player_id  =  T2.player_id GROUP BY T1.first_name;
SELECT t2.Museum_ID ,  t1.name FROM museum_visit_museum AS t1 JOIN museum_visit_visit AS t2 ON t1.Museum_ID  =  t2.Museum_ID GROUP BY t2.Museum_ID ORDER BY count(*) DESC LIMIT 1;
SELECT T2.petid FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid WHERE T1.Lname  =  'Smith';
SELECT count(DISTINCT loser_name) FROM wta_1_matches;
SELECT transcript_date FROM student_transcripts_tracking_Transcripts ORDER BY transcript_date DESC LIMIT 1;
SELECT Airline ,  Abbreviation FROM flight_2_AIRLINES WHERE Country  =  "USA";
SELECT Record_Company FROM orchestra_orchestra GROUP BY Record_Company ORDER BY COUNT(*) DESC LIMIT 1;
SELECT first_name ,  middle_name ,  last_name FROM student_transcripts_tracking_Students ORDER BY date_left ASC LIMIT 1;
SELECT DISTINCT T1.first_name ,  T1.middle_name ,  T1.last_name FROM student_transcripts_tracking_Students AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.student_id  =  T2.student_id JOIN student_transcripts_tracking_Degree_Programs AS T3 ON T2.degree_program_id  =  T3.degree_program_id WHERE T3.degree_summary_name  =  'Bachelor';
SELECT T1.Name FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID;
SELECT count(*) FROM car_1_CARS_DATA WHERE horsepower  >  150;;
SELECT document_id FROM cre_Doc_Template_Mgt_Paragraphs WHERE paragraph_text  =  'Brazil' INTERSECT SELECT document_id FROM cre_Doc_Template_Mgt_Paragraphs WHERE paragraph_text  =  'Ireland';
SELECT name FROM battle_death_battle WHERE bulgarian_commander  =  'Kaloyan' AND latin_commander  =  'Baldwin I';
SELECT T2.transcript_date ,  T1.transcript_id FROM student_transcripts_tracking_Transcript_Contents AS T1 JOIN student_transcripts_tracking_Transcripts AS T2 ON T1.transcript_id  =  T2.transcript_id GROUP BY T1.transcript_id HAVING count(*)  >=  2;
SELECT template_type_description FROM cre_Doc_Template_Mgt_Ref_template_types WHERE template_type_code  =  "AD";
SELECT FlightNo FROM flight_2_FLIGHTS WHERE SourceAirport  =  "APG";
SELECT template_type_code FROM cre_Doc_Template_Mgt_Templates GROUP BY template_type_code ORDER BY count(*) DESC LIMIT 1;
SELECT Hometown FROM course_teach_teacher ORDER BY Age ASC LIMIT 1;
SELECT T1.paragraph_text FROM cre_Doc_Template_Mgt_Paragraphs AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.document_id  =  T2.document_id WHERE T2.document_name  =  "Customer reviews";
SELECT Citizenship FROM singer_singer GROUP BY Citizenship ORDER BY COUNT(*) DESC LIMIT 1;
SELECT Name FROM orchestra_conductor ORDER BY Year_of_Work DESC LIMIT 1;
select count(*) FROM dog_kennels_dogs where dog_id not in ( select dog_id FROM dog_kennels_treatments );
SELECT count(*) ,  hand FROM wta_1_players GROUP BY hand;
SELECT Air_Date FROM tvshow_TV_series WHERE Episode = "A Love of a Lifetime";;
SELECT email_address FROM dog_kennels_Professionals WHERE state  =  'Hawaii' OR state  =  'Wisconsin';
SELECT DISTINCT T1.fname ,  T1.age FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid;
SELECT count(*) FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.DestAirport  =  T2.AirportCode WHERE T2.City  =  "Aberdeen";
SELECT count(*) FROM cre_Doc_Template_Mgt_Templates;
SELECT Name FROM world_1_country WHERE Continent  =  "Asia"  AND population  >  (SELECT max(population) FROM world_1_country WHERE Continent  =  "Africa");
SELECT T2.name ,  count(*) FROM concert_singer_singer_in_concert AS T1 JOIN concert_singer_singer AS T2 ON T1.singer_id  =  T2.singer_id GROUP BY T2.singer_id;
SELECT Abbreviation FROM flight_2_AIRLINES WHERE Airline  =  "JetBlue Airways";
SELECT title ,  Directed_by FROM tvshow_Cartoon ORDER BY Original_air_date;
SELECT DISTINCT T3.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode JOIN world_1_city AS T3 ON T1.Code  =  T3.CountryCode WHERE T2.IsOfficial  =  'T' AND T2.Language  =  'Chinese' AND T1.Continent  =  "Asia";
SELECT Nationality FROM poker_player_people GROUP BY Nationality ORDER BY COUNT(*) DESC LIMIT 1;
SELECT T2.transcript_date ,  T1.transcript_id FROM student_transcripts_tracking_Transcript_Contents AS T1 JOIN student_transcripts_tracking_Transcripts AS T2 ON T1.transcript_id  =  T2.transcript_id GROUP BY T1.transcript_id ORDER BY count(*) ASC LIMIT 1;
SELECT name FROM employee_hire_evaluation_employee WHERE Employee_ID NOT IN (SELECT Employee_ID FROM employee_hire_evaluation_evaluation);
SELECT avg(LifeExpectancy) FROM world_1_country WHERE Name NOT IN (SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" AND T2.IsOfficial  =  "T");
SELECT T2.MakeId ,  T2.Make FROM car_1_CARS_DATA AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Horsepower  >  (SELECT min(Horsepower) FROM car_1_CARS_DATA) AND T1.Cylinders  <=  3;;
SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" INTERSECT SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "French";
SELECT avg(winner_rank) FROM wta_1_matches;
SELECT other_student_details FROM student_transcripts_tracking_Students ORDER BY other_student_details DESC;
SELECT version_number ,  template_type_code FROM cre_Doc_Template_Mgt_Templates WHERE version_number  >  5;
SELECT COUNT(T2.Language) ,  T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode GROUP BY T1.Name HAVING COUNT(*)  >  2;
select t2.concert_name ,  t2.theme ,  count(*) FROM concert_singer_singer_in_concert as t1 JOIN concert_singer_concert as t2 on t1.concert_id  =  t2.concert_id group by t2.concert_id;
select count(*) ,  t1.stuid FROM pets_1_student as t1 JOIN pets_1_has_pet as t2 on t1.stuid  =  t2.stuid group by t1.stuid;
SELECT T2.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id INTERSECT SELECT T2.name FROM network_1_Likes AS T1 JOIN network_1_Highschooler AS T2 ON T1.liked_id  =  T2.id;
SELECT T1.Birth_Date FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID ORDER BY T2.Earnings ASC LIMIT 1;
SELECT name ,  RESULT ,  bulgarian_commander FROM battle_death_battle EXCEPT SELECT T1.name ,  T1.result ,  T1.bulgarian_commander FROM battle_death_battle AS T1 JOIN battle_death_ship AS T2 ON T1.id  =  T2.lost_in_battle WHERE T2.location  =  'English Channel';
SELECT grade FROM network_1_Highschooler;
SELECT cost_of_treatment FROM dog_kennels_Treatments ORDER BY date_of_treatment DESC LIMIT 1;
SELECT T1.Name FROM orchestra_conductor AS T1 JOIN orchestra_orchestra AS T2 ON T1.Conductor_ID  =  T2.Conductor_ID GROUP BY T2.Conductor_ID ORDER BY COUNT(*) DESC LIMIT 1;
SELECT DISTINCT T1.template_type_description FROM cre_Doc_Template_Mgt_Ref_template_types AS T1 JOIN cre_Doc_Template_Mgt_Templates AS T2 ON T1.template_type_code  = T2.template_type_code JOIN cre_Doc_Template_Mgt_Documents AS T3 ON T2.Template_ID  =  T3.template_ID;
SELECT T1.Model FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id ORDER BY T2.horsepower ASC LIMIT 1;;
SELECT T1.country_code ,  T1.first_name FROM wta_1_players AS T1 JOIN wta_1_matches AS T2 ON T1.player_id  =  T2.winner_id WHERE T2.tourney_name  =  'WTA Championships' INTERSECT SELECT T1.country_code ,  T1.first_name FROM wta_1_players AS T1 JOIN wta_1_matches AS T2 ON T1.player_id  =  T2.winner_id WHERE T2.tourney_name  =  'Australian Open';
SELECT min(Number_products) ,  max(Number_products) FROM employee_hire_evaluation_shop;
SELECT student_id ,  count(*) FROM network_1_Likes GROUP BY student_id;
SELECT T1.Id ,  T1.Maker FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id HAVING count(*)  >=  2 INTERSECT SELECT T1.Id ,  T1.Maker FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN car_1_CAR_NAMES AS T3 ON T2.model  =  T3.model GROUP BY T1.Id HAVING count(*)  >  3;;
SELECT avg(loser_age) ,  avg(winner_age) FROM wta_1_matches;
SELECT T1.degree_summary_name FROM student_transcripts_tracking_Degree_Programs AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.degree_program_id  =  T2.degree_program_id GROUP BY T1.degree_summary_name ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM network_1_Highschooler WHERE grade  =  9 OR grade  =  10;
SELECT Name FROM orchestra_conductor ORDER BY Year_of_Work DESC;
SELECT T1.FlightNo FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.DestAirport   =  T2.AirportCode WHERE T2.City  =  "Aberdeen";
SELECT first_name ,  last_name FROM wta_1_players WHERE hand  =  'L' ORDER BY birth_date;
SELECT T1.professional_id ,  T1.role_code ,  T1.first_name FROM dog_kennels_Professionals AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.professional_id  =  T2.professional_id GROUP BY T1.professional_id HAVING count(*)  >=  2;
SELECT LANGUAGE ,  count(*) FROM tvshow_TV_Channel GROUP BY LANGUAGE;
SELECT t2.visitor_id ,  t1.name ,  t1.Level_of_membership FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id GROUP BY t2.visitor_id ORDER BY sum(t2.Total_spent) DESC LIMIT 1;
SELECT sum(SurfaceArea) FROM world_1_country WHERE Continent  =  "Asia" OR Continent  =  "Europe";
SELECT count(*) FROM dog_kennels_Dogs WHERE dog_id NOT IN ( SELECT dog_id FROM dog_kennels_Treatments );
SELECT count(*) ,  country_code FROM wta_1_players GROUP BY country_code;
SELECT sum(Population) ,  avg(LifeExpectancy) ,  Continent FROM world_1_country GROUP BY Continent HAVING avg(LifeExpectancy)  <  72;
SELECT T2.department_name ,  T1.department_id FROM student_transcripts_tracking_Degree_Programs AS T1 JOIN student_transcripts_tracking_Departments AS T2 ON T1.department_id  =  T2.department_id GROUP BY T1.department_id ORDER BY count(*) DESC LIMIT 1;
SELECT max(Final_Table_Made) FROM poker_player_poker_player WHERE Earnings  <  200000;
SELECT DISTINCT state ,  created FROM voter_1_votes;
SELECT DISTINCT T1.model FROM car_1_MODEL_LIST AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.Model  =  T2.Model JOIN car_1_CARS_DATA AS T3 ON T2.MakeId  =  T3.Id JOIN car_1_CAR_MAKERS AS T4 ON T1.Maker  =  T4.Id WHERE T3.weight  <  3500 AND T4.FullName != 'Ford Motor Company';;
SELECT T2.name ,  count(*) FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id;
SELECT avg(age) ,  min(age) ,  max(age) FROM concert_singer_singer WHERE country  =  'France';
SELECT count(*) FROM car_1_COUNTRIES;;
SELECT count(DISTINCT template_id) FROM cre_Doc_Template_Mgt_Documents;
SELECT Region FROM world_1_country AS T1 JOIN world_1_city AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Name  =  "Kabul";
SELECT name ,  age ,  weight FROM dog_kennels_Dogs WHERE abandoned_yn  =  1;
SELECT Episode ,  Rating FROM tvshow_TV_series ORDER BY Rating DESC LIMIT 3;;
SELECT count(*) FROM cre_Doc_Template_Mgt_Documents;
SELECT YEAR FROM wta_1_matches GROUP BY YEAR ORDER BY count(*) DESC LIMIT 1;
SELECT first_name ,  middle_name ,  last_name FROM student_transcripts_tracking_Students ORDER BY date_first_registered ASC LIMIT 1;
SELECT name FROM concert_singer_stadium WHERE stadium_id NOT IN (SELECT stadium_id FROM concert_singer_concert);
SELECT T2.name ,  T2.capacity FROM concert_singer_concert AS T1 JOIN concert_singer_stadium AS T2 ON T1.stadium_id  =  T2.stadium_id WHERE T1.year  >=  2014 GROUP BY T2.stadium_id ORDER BY count(*) DESC LIMIT 1;
SELECT name FROM museum_visit_museum WHERE num_of_staff  >  (SELECT min(num_of_staff) FROM museum_visit_museum WHERE open_year  >  2010);
SELECT avg(num_of_ticket) ,  max(num_of_ticket) FROM museum_visit_visit;
SELECT T1.FlightNo FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.SourceAirport   =  T2.AirportCode WHERE T2.City  =  "Aberdeen";
SELECT name ,  tonnage FROM battle_death_ship ORDER BY name DESC;
select sum(population) ,  avg(surfacearea) FROM world_1_country where continent  =  "north america" and surfacearea  >  3000;
SELECT max(created) FROM voter_1_votes WHERE state  =  'CA';
SELECT Continent FROM world_1_country WHERE Name  =  "Anguilla";
SELECT Episode FROM tvshow_TV_series ORDER BY rating;
SELECT T1.address_id ,  T1.line_1 ,  T1.line_2 FROM student_transcripts_tracking_Addresses AS T1 JOIN student_transcripts_tracking_Students AS T2 ON T1.address_id  =  T2.current_address_id GROUP BY T1.address_id ORDER BY count(*) DESC LIMIT 1;
SELECT document_name ,  template_id FROM cre_Doc_Template_Mgt_Documents WHERE Document_Description LIKE "%w%";
SELECT T2.name FROM concert_singer_singer_in_concert AS T1 JOIN concert_singer_singer AS T2 ON T1.singer_id  =  T2.singer_id JOIN concert_singer_concert AS T3 ON T1.concert_id  =  T3.concert_id WHERE T3.year  =  2014;
SELECT T1.series_name ,  T1.country FROM tvshow_TV_Channel AS T1 JOIN tvshow_cartoon AS T2 ON T1.id = T2.Channel WHERE T2.directed_by  =  'Michael Chang' INTERSECT SELECT T1.series_name ,  T1.country FROM tvshow_TV_Channel AS T1 JOIN tvshow_cartoon AS T2 ON T1.id = T2.Channel WHERE T2.directed_by  =  'Ben Jones';
SELECT template_id ,  version_number ,  template_type_code FROM cre_Doc_Template_Mgt_Templates;
SELECT avg(T2.Earnings) FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID WHERE T1.Height  >  200;
SELECT t1.name ,  t1.age FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id ORDER BY t2.num_of_ticket DESC LIMIT 1;
select t2.makeid ,  t2.make FROM car_1_cars_data as t1 JOIN car_1_car_names as t2 on t1.id  =  t2.makeid where t1.horsepower  >  (select min(horsepower) FROM car_1_cars_data) and t1.cylinders  <  4;;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline GROUP BY T1.Airline HAVING count(*)  >  10;
select t1.countryid ,  t1.countryname FROM car_1_countries as t1 JOIN car_1_car_makers as t2 on t1.countryid  =  t2.country group by t1.countryid having count(*)  >  3 union select t1.countryid ,  t1.countryname FROM car_1_countries as t1 JOIN car_1_car_makers as t2 on t1.countryid  =  t2.country JOIN car_1_model_list as t3 on t2.id  =  t3.maker where t3.model  =  'fiat';;
SELECT count(*) ,  T1.stuid FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid GROUP BY T1.stuid;
SELECT T1.FullName ,  T1.Id ,  count(*) FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id;;
SELECT Title FROM tvshow_Cartoon WHERE Directed_by = "Ben Jones";;
SELECT T1.name ,  T2.date_of_treatment FROM dog_kennels_Dogs AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.dog_id  =  T2.dog_id WHERE T1.breed_code  =  ( SELECT breed_code FROM dog_kennels_Dogs GROUP BY breed_code ORDER BY count(*) ASC LIMIT 1 );
SELECT student_id ,  count(*) FROM network_1_Friend GROUP BY student_id;
SELECT cell_mobile_number FROM student_transcripts_tracking_Students WHERE first_name  =  'Timmothy' AND last_name  =  'Ward';
SELECT count(*) FROM real_estate_properties_Other_Available_Features;
SELECT T1.first_name ,  T1.last_name ,  T2.size_code FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id;
SELECT T1.Name ,  T1.Population FROM world_1_city AS T1 JOIN world_1_countrylanguage AS T2 ON T1.CountryCode  =  T2.CountryCode WHERE T2.Language  =  "English" ORDER BY T1.Population DESC LIMIT 1;
SELECT max(weight) ,  petType FROM pets_1_pets GROUP BY petType;
SELECT max(age) FROM dog_kennels_Dogs;
SELECT T2.Language FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.HeadOfState  =  "Beatrix" AND T2.IsOfficial  =  "T";
select t1.first_name FROM student_transcripts_tracking_students as t1 JOIN student_transcripts_tracking_addresses as t2 on t1.permanent_address_id  =  t2.address_id where t2.country  =  'haiti' or t1.cell_mobile_number  =  '09700166582';
SELECT state FROM dog_kennels_Owners INTERSECT SELECT state FROM dog_kennels_Professionals;
SELECT document_id ,  template_id ,  Document_Description FROM cre_Doc_Template_Mgt_Documents WHERE document_name  =  "Robbin CV";
SELECT count(DISTINCT LANGUAGE) FROM world_1_countrylanguage;
SELECT Name FROM world_1_country WHERE SurfaceArea  >  (SELECT min(SurfaceArea) FROM world_1_country WHERE Continent  =  "Europe");
SELECT country ,  count(*) FROM concert_singer_singer GROUP BY country;
SELECT T1.Name ,  sum(T2.Sales) FROM singer_singer AS T1 JOIN singer_song AS T2 ON T1.Singer_ID  =  T2.Singer_ID GROUP BY T1.Name;
SELECT Pixel_aspect_ratio_PAR ,  country FROM tvshow_tv_channel WHERE LANGUAGE != 'English';
SELECT Weekly_Rank FROM tvshow_TV_series WHERE Episode = "A Love of a Lifetime";;
SELECT DISTINCT T1.Fname FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat' OR T3.pettype  =  'dog';
SELECT min(grade) FROM network_1_Highschooler WHERE id NOT IN (SELECT T1.student_id FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id);
SELECT T3.Name ,  T2.Course FROM course_teach_course_arrange AS T1 JOIN course_teach_course AS T2 ON T1.Course_ID  =  T2.Course_ID JOIN course_teach_teacher AS T3 ON T1.Teacher_ID  =  T3.Teacher_ID ORDER BY T3.Name;
SELECT T2.Name ,  COUNT(*) FROM course_teach_course_arrange AS T1 JOIN course_teach_teacher AS T2 ON T1.Teacher_ID  =  T2.Teacher_ID GROUP BY T2.Name;
SELECT T2.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id HAVING count(*)  >=  3;
SELECT section_name ,  section_description FROM student_transcripts_tracking_Sections;
SELECT T1.Name FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID ORDER BY T2.Earnings DESC;
SELECT T2.property_type_description FROM real_estate_properties_Properties AS T1 JOIN real_estate_properties_Ref_Property_Types AS T2 ON T1.property_type_code  =  T2.property_type_code GROUP BY T1.property_type_code;
select min(weight) FROM car_1_cars_data where cylinders  =  8 and year  =  1974;
SELECT Major_Record_Format FROM orchestra_orchestra GROUP BY Major_Record_Format ORDER BY COUNT(*) ASC;
SELECT T2.name ,  count(*) FROM network_1_Likes AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id;
SELECT Nationality ,  COUNT(*) FROM poker_player_people GROUP BY Nationality;
SELECT count(*) FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T2.petid  =  T3.petid WHERE T1.sex  =  'F' AND T3.pettype  =  'dog';
SELECT count(*) FROM voter_1_votes WHERE state  =  'NY' OR state  =  'CA';
SELECT count(*) FROM car_1_CONTINENTS;;
SELECT Country ,  count(*) FROM tvshow_TV_Channel GROUP BY Country ORDER BY count(*) DESC LIMIT 1;;
SELECT count(DISTINCT T2.Language) FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE  IndepYear  <  1930 AND T2.IsOfficial  =  "T";
SELECT id FROM network_1_Highschooler EXCEPT SELECT student_id FROM network_1_Friend;
SELECT Name FROM world_1_country WHERE Continent  =  "Africa"  AND population  <  (SELECT min(population) FROM world_1_country WHERE Continent  =  "Asia");
SELECT Count(*) ,  T2.FullName ,  T2.id FROM car_1_MODEL_LIST AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.Maker  =  T2.Id GROUP BY T2.id;;
SELECT grade FROM network_1_Highschooler WHERE name  =  "Kyle";
SELECT DISTINCT template_type_code FROM cre_Doc_Template_Mgt_Templates;
SELECT count(*) FROM dog_kennels_Professionals WHERE professional_id NOT IN ( SELECT professional_id FROM dog_kennels_Treatments );
SELECT Name ,  Birth_Date FROM poker_player_people ORDER BY Name ASC;
select t2.department_name ,  t1.department_id FROM student_transcripts_tracking_degree_programs as t1 JOIN student_transcripts_tracking_departments as t2 on t1.department_id  =  t2.department_id group by t1.department_id order by count(*) desc limit 1;
SELECT T2.CountryName FROM car_1_CAR_MAKERS AS T1 JOIN car_1_COUNTRIES AS T2 ON T1.Country  =  T2.CountryId GROUP BY T1.Country ORDER BY Count(*) DESC LIMIT 1;;
select name FROM world_1_city where population between 160000 and 900000;
SELECT count(DISTINCT Nationality) FROM orchestra_conductor;
SELECT T1.lname FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pet_age  =  3 AND T3.pettype  =  'cat';
SELECT count(*) ,  Directed_by FROM tvshow_cartoon GROUP BY Directed_by;
SELECT count(DISTINCT current_address_id) FROM student_transcripts_tracking_Students;
SELECT DISTINCT country FROM concert_singer_singer WHERE age  >  20;
SELECT t1.name FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id JOIN museum_visit_museum AS t3 ON t3.Museum_ID  =  t2.Museum_ID WHERE t3.open_year  <  2009 INTERSECT SELECT t1.name FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id JOIN museum_visit_museum AS t3 ON t3.Museum_ID  =  t2.Museum_ID WHERE t3.open_year  >  2011;
SELECT count(*) FROM wta_1_matches WHERE YEAR  =  2013 OR YEAR  =  2016;
SELECT name FROM museum_visit_museum WHERE Museum_ID NOT IN (SELECT museum_id FROM museum_visit_visit);
SELECT COUNT(*) FROM car_1_CARS_DATA WHERE Accelerate  >  ( SELECT Accelerate FROM car_1_CARS_DATA ORDER BY Horsepower DESC LIMIT 1 );;
SELECT Money_Rank FROM poker_player_poker_player ORDER BY Earnings DESC LIMIT 1;
SELECT count(DISTINCT series_name) ,  count(DISTINCT content) FROM tvshow_TV_Channel;;
SELECT count(*) FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid WHERE T1.age  >  20;
SELECT count(DISTINCT dog_id) FROM dog_kennels_Treatments;
SELECT count(*) FROM battle_death_battle WHERE id NOT IN ( SELECT lost_in_battle FROM battle_death_ship WHERE tonnage  =  '225' );;
SELECT count(DISTINCT country_code) FROM wta_1_players;
SELECT Name FROM world_1_country ORDER BY Population DESC LIMIT 3;
SELECT Name FROM world_1_country WHERE Continent  =  "Asia"  AND population  >  (SELECT min(population) FROM world_1_country WHERE Continent  =  "Africa");
SELECT T1.model FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T2.Weight  <  (SELECT avg(Weight) FROM car_1_CARS_DATA);
SELECT T1.Name FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID ORDER BY T2.Final_Table_Made;
select t1.model FROM car_1_car_names as t1 JOIN car_1_cars_data as t2 on t1.makeid  =  t2.id order by t2.mpg desc limit 1;;
SELECT sum(Population) ,  GovernmentForm FROM world_1_country GROUP BY GovernmentForm HAVING avg(LifeExpectancy)  >  72;
SELECT YEAR FROM concert_singer_concert GROUP BY YEAR ORDER BY count(*) DESC LIMIT 1;
SELECT name ,  RESULT FROM battle_death_battle WHERE bulgarian_commander != 'Boril';
SELECT count(*) FROM course_teach_teacher;
SELECT T1.Abbreviation ,  T1.Country FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline GROUP BY T1.Airline ORDER BY count(*) LIMIT 1;
SELECT count(*) FROM wta_1_players;
SELECT T2.concert_name ,  T2.theme ,  count(*) FROM concert_singer_singer_in_concert AS T1 JOIN concert_singer_concert AS T2 ON T1.concert_id  =  T2.concert_id GROUP BY T2.concert_id;
SELECT min(loser_rank) FROM wta_1_matches;
SELECT Name FROM singer_singer WHERE Citizenship != "France";
SELECT T1.template_type_code FROM cre_Doc_Template_Mgt_Templates AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.template_id  =  T2.template_id WHERE T2.document_name  =  "Data base";
SELECT count(*) FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.DestAirport  =  T2.AirportCode JOIN flight_2_AIRPORTS AS T3 ON T1.SourceAirport  =  T3.AirportCode WHERE T2.City  =  "Ashley" AND T3.City  =  "Aberdeen";
SELECT name ,  grade FROM network_1_Highschooler;
SELECT T2.Language FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.GovernmentForm  =  "Republic" GROUP BY T2.Language HAVING COUNT(*)  =  1;
SELECT count(*) FROM tvshow_TV_Channel WHERE LANGUAGE = "English";;
SELECT name FROM employee_hire_evaluation_shop WHERE number_products  >  (SELECT avg(number_products) FROM employee_hire_evaluation_shop);
SELECT T1.country FROM tvshow_TV_Channel AS T1 JOIN tvshow_cartoon AS T2 ON T1.id = T2.Channel WHERE T2.written_by  =  'Todd Casey';
SELECT T1.countryId ,  T1.CountryName FROM car_1_Countries AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.CountryId  =  T2.Country GROUP BY T1.countryId HAVING count(*)  >  3 UNION SELECT T1.countryId ,  T1.CountryName FROM car_1_Countries AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.CountryId  =  T2.Country JOIN car_1_MODEL_LIST AS T3 ON T2.Id  =  T3.Maker WHERE T3.Model  =  'fiat';;
SELECT T3.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id JOIN network_1_Highschooler AS T3 ON T1.friend_id  =  T3.id WHERE T2.name  =  "Kyle";
SELECT song_name ,  song_release_year FROM concert_singer_singer ORDER BY age LIMIT 1;
SELECT T2.Make ,  T1.Year FROM car_1_CARS_DATA AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T1.Year  =  (SELECT min(YEAR) FROM car_1_CARS_DATA);;
SELECT winner_name FROM wta_1_matches WHERE YEAR  =  2013 INTERSECT SELECT winner_name FROM wta_1_matches WHERE YEAR  =  2016;
SELECT t1.name FROM employee_hire_evaluation_employee AS t1 JOIN employee_hire_evaluation_evaluation AS t2 ON t1.Employee_ID  =  t2.Employee_ID ORDER BY t2.bonus DESC LIMIT 1;
SELECT count(*) FROM cre_Doc_Template_Mgt_Paragraphs;
SELECT T1.cost_of_treatment ,  T2.treatment_type_description FROM dog_kennels_Treatments AS T1 JOIN dog_kennels_treatment_types AS T2 ON T1.treatment_type_code  =  T2.treatment_type_code;
select count(*) ,  t2.fullname FROM car_1_model_list as t1 JOIN car_1_car_makers as t2 on t1.maker  =  t2.id group by t2.id;;
SELECT t1.name FROM employee_hire_evaluation_employee AS t1 JOIN employee_hire_evaluation_evaluation AS t2 ON t1.Employee_ID  =  t2.Employee_ID GROUP BY t2.Employee_ID ORDER BY count(*) DESC LIMIT 1;
SELECT T1.series_name FROM tvshow_TV_Channel AS T1 JOIN tvshow_Cartoon AS T2 ON T1.id = T2.Channel WHERE T2.Title = "The Rise of the Blue Beetle!";;
SELECT Orchestra FROM orchestra_orchestra WHERE Orchestra_ID NOT IN (SELECT Orchestra_ID FROM orchestra_performance);
SELECT Name FROM singer_singer ORDER BY Net_Worth_Millions DESC LIMIT 1;
SELECT count(*) FROM world_1_country WHERE GovernmentForm  =  "Republic";
SELECT T3.area_code FROM voter_1_contestants AS T1 JOIN voter_1_votes AS T2 ON T1.contestant_number  =  T2.contestant_number JOIN voter_1_area_code_state AS T3 ON T2.state  =  T3.state WHERE T1.contestant_name  =  'Tabatha Gehling' INTERSECT SELECT T3.area_code FROM voter_1_contestants AS T1 JOIN voter_1_votes AS T2 ON T1.contestant_number  =  T2.contestant_number JOIN voter_1_area_code_state AS T3 ON T2.state  =  T3.state WHERE T1.contestant_name  =  'Kelly Clauss';
SELECT grade FROM network_1_Highschooler GROUP BY grade ORDER BY count(*) DESC LIMIT 1;
SELECT T1.Name FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID WHERE T2.Earnings  >  300000;
SELECT Record_Company ,  COUNT(*) FROM orchestra_orchestra GROUP BY Record_Company;
SELECT museum_id ,  name FROM museum_visit_museum ORDER BY num_of_staff DESC LIMIT 1;
select max(mpg) FROM car_1_cars_data where cylinders  =  8 or year  <  1980;
SELECT name ,  date FROM battle_death_battle;
select name FROM dog_kennels_dogs where dog_id not in ( select dog_id FROM dog_kennels_treatments group by dog_id having sum(cost_of_treatment)  >  1000 );
SELECT DISTINCT T1.Maker FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker JOIN car_1_CAR_NAMES AS T3 ON T2.model  =  T3.model JOIN car_1_CARS_DATA AS T4 ON T3.MakeId  =  T4.id WHERE T4.year  =  '1970';;
SELECT count(*) FROM flight_2_Flights AS T1 JOIN flight_2_Airports AS T2 ON T1.DestAirport  =  T2.AirportCode WHERE T2.city  =  "Aberdeen" OR T2.city  =  "Abilene";
SELECT Hometown ,  COUNT(*) FROM course_teach_teacher GROUP BY Hometown;
SELECT count(*) FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker WHERE T1.FullName  =  'American Motor Company';;
SELECT max(Accelerate) ,  Cylinders FROM car_1_CARS_DATA GROUP BY Cylinders;;
SELECT count(*) FROM flight_2_FLIGHTS WHERE DestAirport  =  "ATO";
SELECT T1.template_type_code FROM cre_Doc_Template_Mgt_Templates AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.template_id  =  T2.template_id GROUP BY T1.template_type_code ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM cre_Doc_Template_Mgt_Templates WHERE template_type_code  =  "CV";
SELECT manager_name ,  district FROM employee_hire_evaluation_shop ORDER BY number_products DESC LIMIT 1;
SELECT count(*) FROM flight_2_FLIGHTS;
SELECT T1.Accelerate FROM car_1_CARS_DATA AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T2.Make  =  'amc hornet sportabout (sw)';;
SELECT FlightNo FROM flight_2_FLIGHTS WHERE DestAirport  =  "APG";
SELECT pettype ,  weight FROM pets_1_pets ORDER BY pet_age LIMIT 1;
SELECT Nationality FROM poker_player_people GROUP BY Nationality HAVING COUNT(*)  >=  2;
SELECT T2.created ,  T2.state ,  T2.phone_number FROM voter_1_contestants AS T1 JOIN voter_1_votes AS T2 ON T1.contestant_number  =  T2.contestant_number WHERE T1.contestant_name  =  'Tabatha Gehling';
SELECT grade ,  count(*) FROM network_1_Highschooler GROUP BY grade;
SELECT date_arrived ,  date_departed FROM dog_kennels_Dogs;
SELECT count(DISTINCT winner_name) FROM wta_1_matches WHERE tourney_name  =  'WTA Championships' AND winner_hand  =  'L';
SELECT Name FROM world_1_country ORDER BY Population ASC LIMIT 3;
SELECT T2.Episode FROM tvshow_TV_Channel AS T1 JOIN tvshow_TV_series AS T2 ON T1.id = T2.Channel WHERE T1.series_name = "Sky Radio";;
SELECT DISTINCT T2.semester_id FROM student_transcripts_tracking_Degree_Programs AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.degree_program_id  =  T2.degree_program_id WHERE degree_summary_name  =  'Master' INTERSECT SELECT DISTINCT T2.semester_id FROM student_transcripts_tracking_Degree_Programs AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.degree_program_id  =  T2.degree_program_id WHERE degree_summary_name  =  'Bachelor';
SELECT count(DISTINCT professional_id) FROM dog_kennels_Treatments;
SELECT avg(num_of_staff) FROM museum_visit_museum WHERE open_year  <  2009;
SELECT Record_Company FROM orchestra_orchestra WHERE Year_of_Founded  <  2003 INTERSECT SELECT Record_Company FROM orchestra_orchestra WHERE Year_of_Founded  >  2003;
SELECT T1.Name ,  T2.Orchestra FROM orchestra_conductor AS T1 JOIN orchestra_orchestra AS T2 ON T1.Conductor_ID  =  T2.Conductor_ID;
SELECT count(*) FROM flight_2_AIRLINES;
SELECT COUNT(T2.Language) FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.Name  =  "Aruba";
SELECT count(*) FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id WHERE T2.name  =  "Kyle";
SELECT count(*) FROM museum_visit_visitor WHERE age  <  30;
SELECT count(*) FROM wta_1_matches;
SELECT max(killed) ,  min(killed) FROM battle_death_death;
SELECT T1.semester_name ,  T1.semester_id FROM student_transcripts_tracking_Semesters AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.semester_id  =  T2.semester_id GROUP BY T1.semester_id ORDER BY count(*) DESC LIMIT 1;
SELECT template_id FROM cre_Doc_Template_Mgt_Templates WHERE template_type_code  =  "PP" OR template_type_code  =  "PPT";
SELECT Package_Option FROM tvshow_TV_Channel WHERE series_name = "Sky Radio";;
SELECT avg(T2.edispl) FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T1.Model  =  'volvo';;
select t2.name ,  t2.capacity FROM concert_singer_concert as t1 JOIN concert_singer_stadium as t2 on t1.stadium_id  =  t2.stadium_id where t1.year  >  2013 group by t2.stadium_id order by count(*) desc limit 1;
SELECT CountryCode ,  max(Percentage) FROM world_1_countrylanguage WHERE LANGUAGE  =  "Spanish" GROUP BY CountryCode;
SELECT course_description FROM student_transcripts_tracking_Courses WHERE course_name  =  'math';
SELECT document_id FROM cre_Doc_Template_Mgt_Paragraphs GROUP BY document_id HAVING count(*)  >=  2;
SELECT max(SHARE) ,  min(SHARE) FROM orchestra_performance WHERE TYPE != "Live final";
SELECT Num_of_Staff ,  Open_Year FROM museum_visit_museum WHERE name  =  'Plaza Museum';
SELECT template_type_code ,  template_type_description FROM cre_Doc_Template_Mgt_Ref_template_types;
SELECT first_name ,  last_name ,  email_address FROM dog_kennels_Owners WHERE state LIKE '%North%';
SELECT T1.id ,  T1.name FROM battle_death_battle AS T1 JOIN battle_death_ship AS T2 ON T1.id  =  T2.lost_in_battle JOIN battle_death_death AS T3 ON T2.id  =  T3.caused_by_ship_id GROUP BY T1.id HAVING sum(T3.killed)  >  10;
SELECT avg(LifeExpectancy) FROM world_1_country WHERE Region  =  "Central Africa";
SELECT Citizenship FROM singer_singer WHERE Birth_Year  <  1945 INTERSECT SELECT Citizenship FROM singer_singer WHERE Birth_Year  >  1955;
SELECT T1.Name FROM orchestra_conductor AS T1 JOIN orchestra_orchestra AS T2 ON T1.Conductor_ID  =  T2.Conductor_ID WHERE Year_of_Founded  >  2008;
SELECT count(*) ,  city FROM employee_hire_evaluation_employee GROUP BY city;
SELECT T1.AirportCode FROM flight_2_AIRPORTS AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.AirportCode  =  T2.DestAirport OR T1.AirportCode  =  T2.SourceAirport GROUP BY T1.AirportCode ORDER BY count(*) LIMIT 1;
SELECT CountryName FROM car_1_countries EXCEPT SELECT T1.CountryName FROM car_1_countries AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.countryId  =  T2.Country;;
SELECT T1.contestant_number , T1.contestant_name FROM voter_1_contestants AS T1 JOIN voter_1_votes AS T2 ON T1.contestant_number  =  T2.contestant_number GROUP BY T1.contestant_number HAVING count(*)  >=  2;
SELECT sum(t2.Total_spent) FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id WHERE t1.Level_of_membership  =  1;
SELECT avg(pet_age) ,  max(pet_age) ,  pettype FROM pets_1_pets GROUP BY pettype;
SELECT count(*) FROM car_1_CARS_DATA WHERE YEAR  =  1980;;
SELECT package_option FROM tvshow_TV_Channel WHERE id NOT IN (SELECT channel FROM tvshow_cartoon WHERE directed_by  =  'Ben Jones');
SELECT T1.AirportCode FROM flight_2_AIRPORTS AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.AirportCode  =  T2.DestAirport OR T1.AirportCode  =  T2.SourceAirport GROUP BY T1.AirportCode ORDER BY count(*) DESC LIMIT 1;
SELECT T2.template_id FROM cre_Doc_Template_Mgt_Ref_template_types AS T1 JOIN cre_Doc_Template_Mgt_Templates AS T2 ON T1.template_type_code  = T2.template_type_code WHERE T1.template_type_description  =  "Presentation";
SELECT count(*) FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.SourceAirport  =  T2.AirportCode WHERE T2.City  =  "Aberdeen";
SELECT Content FROM tvshow_TV_Channel WHERE series_name = "Sky Radio";;
select distinct year FROM car_1_cars_data where weight between 3000 and 4000;;
SELECT Record_Company FROM orchestra_orchestra ORDER BY Year_of_Founded DESC;
SELECT count(*) FROM orchestra_conductor;
SELECT T1.fname ,  T1.age FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'dog' AND T1.stuid NOT IN (SELECT T1.stuid FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat');
SELECT count(*) FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T2.Airline  =  T1.uid WHERE T1.Airline  =  "United Airlines" AND T2.SourceAirport  =  "AHD";
SELECT AirportName FROM flight_2_AIRPORTS WHERE AirportCode  =  "AKO";
SELECT country FROM concert_singer_singer WHERE age  >  40 INTERSECT SELECT country FROM concert_singer_singer WHERE age  <  30;
SELECT document_id ,  count(*) FROM cre_Doc_Template_Mgt_Paragraphs GROUP BY document_id ORDER BY document_id;
SELECT Birth_Year ,  Citizenship FROM singer_singer;
SELECT Year_of_Founded FROM orchestra_orchestra AS T1 JOIN orchestra_performance AS T2 ON T1.Orchestra_ID  =  T2.Orchestra_ID GROUP BY T2.Orchestra_ID HAVING COUNT(*)  >  1;
SELECT avg(injured) FROM battle_death_death;
SELECT Name FROM singer_singer ORDER BY Net_Worth_Millions ASC;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.DestAirport  =  "AHD";
SELECT count(*) FROM world_1_country WHERE continent  =  "Asia";
SELECT winner_name ,  loser_name FROM wta_1_matches ORDER BY minutes DESC LIMIT 1;
SELECT T1.FlightNo FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRLINES AS T2 ON T2.uid  =  T1.Airline WHERE T2.Airline  =  "United Airlines";
SELECT Hometown FROM course_teach_teacher GROUP BY Hometown ORDER BY COUNT(*) DESC LIMIT 1;
SELECT winner_name ,  winner_rank_points FROM wta_1_matches GROUP BY winner_name ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM network_1_Likes AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id WHERE T2.name  =  "Kyle";
SELECT count(*) FROM student_transcripts_tracking_Transcripts;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline GROUP BY T1.Airline ORDER BY count(*) DESC LIMIT 1;
SELECT DISTINCT T1.first_name ,  T3.treatment_type_description FROM dog_kennels_professionals AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.professional_id  =  T2.professional_id JOIN dog_kennels_Treatment_types AS T3 ON T2.treatment_type_code  =  T3.treatment_type_code;
SELECT LANGUAGE FROM world_1_countrylanguage GROUP BY LANGUAGE ORDER BY count(*) DESC LIMIT 1;
SELECT DISTINCT winner_name ,  winner_rank FROM wta_1_matches ORDER BY winner_age LIMIT 3;
SELECT Maker ,  Model FROM car_1_MODEL_LIST;;
SELECT DISTINCT T1.Region FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" OR T2.Language  =  "Dutch";
SELECT sum(Population) FROM world_1_country WHERE Name NOT IN (SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English");
SELECT count(*) ,  t2.name FROM employee_hire_evaluation_hiring AS t1 JOIN employee_hire_evaluation_shop AS t2 ON t1.shop_id  =  t2.shop_id GROUP BY t2.name;
SELECT T2.horsepower ,  T1.Make FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id WHERE T2.cylinders  =  3 ORDER BY T2.horsepower DESC LIMIT 1;;
SELECT min(Version_Number) ,  template_type_code FROM cre_Doc_Template_Mgt_Templates;
SELECT district FROM employee_hire_evaluation_shop WHERE Number_products  <  3000 INTERSECT SELECT district FROM employee_hire_evaluation_shop WHERE Number_products  >  10000;
SELECT T2.name FROM network_1_Likes AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id HAVING count(*)  >=  2;
SELECT Name ,  population ,  HeadOfState FROM world_1_country ORDER BY SurfaceArea DESC LIMIT 1;
SELECT line_1 ,  line_2 FROM student_transcripts_tracking_addresses;
SELECT name FROM concert_singer_stadium EXCEPT SELECT T2.name FROM concert_singer_concert AS T1 JOIN concert_singer_stadium AS T2 ON T1.stadium_id  =  T2.stadium_id WHERE T1.year  =  2014;
SELECT T1.FullName ,  T1.Id FROM car_1_CAR_MAKERS AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Id  =  T2.Maker GROUP BY T1.Id HAVING count(*)  >  3;;
SELECT stuid FROM pets_1_student EXCEPT SELECT T1.stuid FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat';
SELECT name FROM employee_hire_evaluation_employee ORDER BY age;
SELECT T1.CountryName ,  T1.CountryId FROM car_1_COUNTRIES AS T1 JOIN car_1_CAR_MAKERS AS T2 ON T1.CountryId  =  T2.Country GROUP BY T1.CountryId HAVING count(*)  >=  1;;
SELECT id FROM tvshow_TV_Channel EXCEPT SELECT channel FROM tvshow_cartoon WHERE directed_by  =  'Ben Jones';
SELECT Name FROM world_1_country WHERE IndepYear  >  1950;
SELECT T1.treatment_type_description FROM dog_kennels_Treatment_types AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.treatment_type_code  =  T2.treatment_type_code GROUP BY T1.treatment_type_code ORDER BY sum(cost_of_treatment) ASC LIMIT 1;
SELECT zip_postcode FROM student_transcripts_tracking_Addresses WHERE city  =  'Port Chelsea';
SELECT city FROM employee_hire_evaluation_employee WHERE age  <  30 GROUP BY city HAVING count(*)  >  1;
SELECT id FROM tvshow_tv_channel GROUP BY country HAVING count(*)  >  2;
select contestant_name FROM voter_1_contestants where contestant_name like "%al%";
SELECT count(*) FROM cre_Doc_Template_Mgt_Paragraphs AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.document_ID  =  T2.document_ID WHERE T2.document_name  =  'Summer Show';
SELECT count(*) FROM student_transcripts_tracking_Departments AS T1 JOIN student_transcripts_tracking_Degree_Programs AS T2 ON T1.department_id  =  T2.department_id WHERE T1.department_name  =  'engineer';
SELECT count(*) FROM car_1_CARS_DATA WHERE Cylinders  >  4;;
SELECT count(*) ,  student_course_id FROM student_transcripts_tracking_Transcript_Contents GROUP BY student_course_id ORDER BY count(*) DESC LIMIT 1;
SELECT Name FROM poker_player_people WHERE People_ID NOT IN (SELECT People_ID FROM poker_player_poker_player);
SELECT T1.cylinders FROM car_1_CARS_DATA AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.Id  =  T2.MakeId WHERE T2.Model  =  'volvo' ORDER BY T1.accelerate ASC LIMIT 1;;
SELECT sum(tours) ,  ranking_date FROM wta_1_rankings GROUP BY ranking_date;
SELECT count(*) FROM flight_2_AIRLINES WHERE Country  =  "USA";
SELECT count(*) FROM concert_singer_concert WHERE YEAR  =  2014 OR YEAR  =  2015;
SELECT count(*) FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRLINES AS T2 ON T1.Airline  =  T2.uid WHERE T2.Airline = "JetBlue Airways";
SELECT Name FROM course_teach_teacher WHERE Age  =  32 OR Age  =  33;
SELECT COUNT(*) FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.Name  =  "Afghanistan" AND IsOfficial  =  "T";
SELECT avg(age) FROM museum_visit_visitor WHERE Level_of_membership  <=  4;
SELECT tourney_name FROM wta_1_matches GROUP BY tourney_name HAVING count(*)  >  10;
SELECT petid ,  weight FROM pets_1_pets WHERE pet_age  >  1;
SELECT LANGUAGE ,  count(*) FROM tvshow_TV_Channel GROUP BY LANGUAGE ORDER BY count(*) ASC LIMIT 1;;
SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.SourceAirport  =  "CVO" EXCEPT SELECT T1.Airline FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.uid  =  T2.Airline WHERE T2.SourceAirport  =  "APG";
SELECT note FROM battle_death_death WHERE note LIKE '%East%';
SELECT CountryCode FROM world_1_countrylanguage EXCEPT SELECT CountryCode FROM world_1_countrylanguage WHERE LANGUAGE  =  "English";
SELECT template_type_code FROM cre_Doc_Template_Mgt_Ref_template_types WHERE template_type_description  =  "Book";
SELECT * FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" AND IsOfficial  =  "T" UNION SELECT * FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "Dutch" AND IsOfficial  =  "T";
SELECT T2.id ,  T2.name FROM battle_death_death AS T1 JOIN battle_death_ship AS t2 ON T1.caused_by_ship_id  =  T2.id GROUP BY T2.id ORDER BY count(*) DESC LIMIT 1;
SELECT  T1.course_name FROM student_transcripts_tracking_Courses AS T1 JOIN student_transcripts_tracking_Student_Enrolment_Courses AS T2 ON T1.course_id  =  T2.course_id GROUP BY T1.course_name ORDER BY count(*) DESC LIMIT 1;
SELECT T1.template_id ,  T2.Template_Type_Code FROM cre_Doc_Template_Mgt_Documents AS T1 JOIN cre_Doc_Template_Mgt_Templates AS T2 ON T1.template_id  =  T2.template_id GROUP BY T1.template_id ORDER BY count(*) DESC LIMIT 1;
select name FROM course_teach_teacher where hometown != "little lever urban district";
SELECT Title FROM tvshow_Cartoon WHERE Directed_by = "Ben Jones" OR Directed_by = "Brandon Vietti";;
SELECT DISTINCT T1.first_name ,  T1.last_name FROM dog_kennels_Professionals AS T1 JOIN dog_kennels_Treatments AS T2 WHERE cost_of_treatment  <  ( SELECT avg(cost_of_treatment) FROM dog_kennels_Treatments );
SELECT template_type_code FROM cre_Doc_Template_Mgt_Templates EXCEPT SELECT template_type_code FROM cre_Doc_Template_Mgt_Templates AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.template_id  =  T2.template_id;
SELECT count(DISTINCT pettype) FROM pets_1_pets;
SELECT T2.Title FROM tvshow_TV_Channel AS T1 JOIN tvshow_Cartoon AS T2 ON T1.id = T2.Channel WHERE T1.series_name = "Sky Radio";;
SELECT Citizenship ,  COUNT(*) FROM singer_singer GROUP BY Citizenship;
SELECT name ,  country ,  age FROM concert_singer_singer ORDER BY age DESC;
SELECT first_name ,  birth_date FROM wta_1_players WHERE country_code  =  'USA';
SELECT T2.Title ,  T1.Name FROM singer_singer AS T1 JOIN singer_song AS T2 ON T1.Singer_ID  =  T2.Singer_ID;
SELECT AirportCode ,  AirportName FROM flight_2_AIRPORTS WHERE city  =  "Anthony";
SELECT Name FROM orchestra_conductor WHERE Nationality != 'USA';
SELECT first_name FROM dog_kennels_Professionals UNION SELECT first_name FROM dog_kennels_Owners EXCEPT SELECT name FROM dog_kennels_Dogs;
SELECT department_description FROM student_transcripts_tracking_Departments WHERE department_name LIKE '%computer%';
SELECT Name FROM course_teach_teacher ORDER BY Age ASC;
SELECT count(*) FROM singer_singer;
SELECT T2.name ,  count(*) FROM concert_singer_concert AS T1 JOIN concert_singer_stadium AS T2 ON T1.stadium_id  =  T2.stadium_id GROUP BY T1.stadium_id;
SELECT T1.Model FROM car_1_CAR_NAMES AS T1 JOIN car_1_CARS_DATA AS T2 ON T1.MakeId  =  T2.Id ORDER BY T2.mpg DESC LIMIT 1;;
SELECT count(*) ,  YEAR FROM wta_1_matches GROUP BY YEAR;
SELECT sum(Population) FROM world_1_city WHERE District  =  "Gelderland";
SELECT grade FROM network_1_Highschooler GROUP BY grade HAVING count(*)  >=  4;
SELECT DISTINCT T1.course_name FROM student_transcripts_tracking_Courses AS T1 JOIN student_transcripts_tracking_Student_Enrolment_Courses AS T2 ON T1.course_id  =  T2.course_id;
SELECT count(*) FROM poker_player_poker_player;
SELECT T1.first_name ,  T1.country_code ,  T1.birth_date FROM wta_1_players AS T1 JOIN wta_1_matches AS T2 ON T1.player_id  =  T2.winner_id ORDER BY T2.winner_rank_points DESC LIMIT 1;
SELECT avg(horsepower) FROM car_1_CARS_DATA WHERE YEAR  <  1980;;
SELECT count(*) ,   max(Percentage) FROM world_1_countrylanguage WHERE LANGUAGE  =  "Spanish" GROUP BY CountryCode;
SELECT document_id ,  document_name ,  document_description FROM cre_Doc_Template_Mgt_Documents;
SELECT count(DISTINCT Nationality) FROM poker_player_people;
SELECT T1.owner_id ,  T2.first_name ,  T2.last_name FROM dog_kennels_Dogs AS T1 JOIN dog_kennels_Owners AS T2 ON T1.owner_id  =  T2.owner_id GROUP BY T1.owner_id ORDER BY count(*) DESC LIMIT 1;
SELECT Name FROM world_1_country WHERE continent  =  "Europe" AND Population  =  "80000";
SELECT T1.last_name FROM student_transcripts_tracking_Students AS T1 JOIN student_transcripts_tracking_Addresses AS T2 ON T1.current_address_id  =  T2.address_id WHERE T2.state_province_county  =  'NorthCarolina' EXCEPT SELECT DISTINCT T3.last_name FROM student_transcripts_tracking_Students AS T3 JOIN student_transcripts_tracking_Student_Enrolment AS T4 ON T3.student_id  =  T4.student_id;
SELECT Name FROM singer_singer WHERE Singer_ID NOT IN (SELECT Singer_ID FROM singer_song);
SELECT T1.country_code ,  T1.first_name FROM wta_1_players AS T1 JOIN wta_1_rankings AS T2 ON T1.player_id  =  T2.player_id ORDER BY T2.tours DESC LIMIT 1;
SELECT name FROM museum_visit_visitor WHERE Level_of_membership  >  4 ORDER BY Level_of_membership DESC;
SELECT DISTINCT T1.id ,  T1.name FROM battle_death_battle AS T1 JOIN battle_death_ship AS T2 ON T1.id  =  T2.lost_in_battle WHERE T2.ship_type  =  'Brig';
SELECT T1.area_code FROM voter_1_area_code_state AS T1 JOIN voter_1_votes AS T2 ON T1.state  =  T2.state GROUP BY T1.area_code ORDER BY count(*) DESC LIMIT 1;
SELECT professional_id ,  last_name ,  cell_number FROM dog_kennels_Professionals WHERE state  =  'Indiana' UNION SELECT T1.professional_id ,  T1.last_name ,  T1.cell_number FROM dog_kennels_Professionals AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.professional_id  =  T2.professional_id GROUP BY T1.professional_id HAVING count(*)  >  2;
SELECT T1.date_of_treatment ,  T2.first_name FROM dog_kennels_Treatments AS T1 JOIN dog_kennels_Professionals AS T2 ON T1.professional_id  =  T2.professional_id;
SELECT COUNT( DISTINCT Continent) FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "Chinese";
SELECT count(*) FROM flight_2_AIRLINES AS T1 JOIN flight_2_FLIGHTS AS T2 ON T2.Airline  =  T1.uid WHERE T1.Airline  =  "United Airlines" AND T2.DestAirport  =  "ASY";
SELECT name FROM network_1_Highschooler EXCEPT SELECT T2.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id;
SELECT T2.document_name FROM cre_Doc_Template_Mgt_Templates AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.template_id  =  T2.template_id WHERE T1.template_type_code  =  "BK";
SELECT T2.Language FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.Continent  =  "Asia" GROUP BY T2.Language ORDER BY COUNT (*) DESC LIMIT 1;
SELECT first_name ,  country_code FROM wta_1_players ORDER BY birth_date LIMIT 1;
SELECT package_option ,  series_name FROM tvshow_TV_Channel WHERE hight_definition_TV  =  "yes";
SELECT avg(mpg) FROM car_1_CARS_DATA WHERE Cylinders  =  4;;
SELECT LANGUAGE ,  CountryCode ,  max(Percentage) FROM world_1_countrylanguage GROUP BY CountryCode;
SELECT Name ,  SurfaceArea FROM world_1_country ORDER BY SurfaceArea DESC LIMIT 5;
SELECT T2.Language FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T1.Name  =  "Aruba" ORDER BY Percentage DESC LIMIT 1;
SELECT T1.Fname FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'cat' INTERSECT SELECT T1.Fname FROM pets_1_student AS T1 JOIN pets_1_has_pet AS T2 ON T1.stuid  =  T2.stuid JOIN pets_1_pets AS T3 ON T3.petid  =  T2.petid WHERE T3.pettype  =  'dog';
SELECT Name FROM world_1_country WHERE Continent  =  "Asia" ORDER BY LifeExpectancy LIMIT 1;
SELECT T1.Name FROM orchestra_conductor AS T1 JOIN orchestra_orchestra AS T2 ON T1.Conductor_ID  =  T2.Conductor_ID GROUP BY T2.Conductor_ID HAVING COUNT(*)  >  1;
SELECT name ,  country FROM concert_singer_singer WHERE song_name LIKE '%Hey%';
SELECT Name ,  Population ,  LifeExpectancy FROM world_1_country WHERE Continent  =  "Asia" ORDER BY SurfaceArea DESC LIMIT 1;
SELECT T1.student_id ,  T1.first_name ,  T1.middle_name ,  T1.last_name ,  count(*) ,  T1.student_id FROM student_transcripts_tracking_Students AS T1 JOIN student_transcripts_tracking_Student_Enrolment AS T2 ON T1.student_id  =  T2.student_id GROUP BY T1.student_id ORDER BY count(*) DESC LIMIT 1;
SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode GROUP BY T1.Name ORDER BY COUNT(*) DESC LIMIT 1;
SELECT Country FROM flight_2_AIRLINES WHERE Airline  =  "JetBlue Airways";
SELECT count(*) FROM car_1_CAR_MAKERS AS T1 JOIN car_1_COUNTRIES AS T2 ON T1.Country  =  T2.CountryId WHERE T2.CountryName  =  'france';;
SELECT count(DISTINCT GovernmentForm) FROM world_1_country WHERE Continent  =  "Africa";
select t1.name FROM world_1_country as t1 JOIN world_1_countrylanguage as t2 on t1.code  =  t2.countrycode where t2.language  =  "english" and isofficial  =  "t" union select t1.name FROM world_1_country as t1 JOIN world_1_countrylanguage as t2 on t1.code  =  t2.countrycode where t2.language  =  "dutch" and isofficial  =  "t";
select max(capacity), average FROM concert_singer_stadium;
SELECT T1.Continent ,  count(*) FROM car_1_CONTINENTS AS T1 JOIN car_1_COUNTRIES AS T2 ON T1.ContId  =  T2.continent JOIN car_1_car_makers AS T3 ON T2.CountryId  =  T3.Country GROUP BY T1.Continent;;
SELECT country FROM tvshow_TV_Channel EXCEPT SELECT T1.country FROM tvshow_TV_Channel AS T1 JOIN tvshow_cartoon AS T2 ON T1.id = T2.Channel WHERE T2.written_by  =  'Todd Casey';
SELECT count(*) FROM flight_2_FLIGHTS AS T1 JOIN flight_2_AIRPORTS AS T2 ON T1.DestAirport  =  T2.AirportCode JOIN flight_2_AIRLINES AS T3 ON T3.uid  =  T1.Airline WHERE T2.City  =  "Aberdeen" AND T3.Airline  =  "United Airlines";
SELECT T2.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id GROUP BY T1.student_id ORDER BY count(*) DESC LIMIT 1;
SELECT City ,  Country FROM flight_2_AIRPORTS WHERE AirportName  =  "Alton";
SELECT count(DISTINCT degree_summary_name) FROM student_transcripts_tracking_Degree_Programs;
SELECT COUNT(*) FROM (SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "English" INTERSECT SELECT T1.Name FROM world_1_country AS T1 JOIN world_1_countrylanguage AS T2 ON T1.Code  =  T2.CountryCode WHERE T2.Language  =  "Dutch");
SELECT count(*) FROM voter_1_contestants WHERE contestant_number NOT IN ( SELECT contestant_number FROM voter_1_votes );
SELECT name FROM world_1_city WHERE Population BETWEEN 160000 AND 900000;
SELECT first_name ,  last_name FROM wta_1_players ORDER BY birth_date;
SELECT T2.Money_Rank FROM poker_player_people AS T1 JOIN poker_player_poker_player AS T2 ON T1.People_ID  =  T2.People_ID ORDER BY T1.Height DESC LIMIT 1;
SELECT Name FROM poker_player_people WHERE Nationality != "Russia";
SELECT T1.horsepower FROM car_1_CARS_DATA AS T1 ORDER BY T1.accelerate DESC LIMIT 1;;
SELECT DISTINCT T2.Model FROM car_1_CAR_NAMES AS T1 JOIN car_1_MODEL_LIST AS T2 ON T1.Model  =  T2.Model JOIN car_1_CAR_MAKERS AS T3 ON T2.Maker  =  T3.Id JOIN car_1_CARS_DATA AS T4 ON T1.MakeId  =  T4.Id WHERE T3.FullName  =  'General Motors' OR T4.weight  >  3500;;
SELECT t1.id ,  t1.name ,  t1.age FROM museum_visit_visitor AS t1 JOIN museum_visit_visit AS t2 ON t1.id  =  t2.visitor_id GROUP BY t1.id HAVING count(*)  >  1;
select count(*) FROM concert_singer_concert where stadium_id = (select stadium_id FROM concert_singer_stadium order by capacity desc limit 1);
SELECT count(*) FROM concert_singer_singer;
SELECT T1.CountryName FROM car_1_COUNTRIES AS T1 JOIN car_1_CONTINENTS AS T2 ON T1.Continent  =  T2.ContId JOIN car_1_CAR_MAKERS AS T3 ON T1.CountryId  =  T3.Country WHERE T2.Continent  =  'europe' GROUP BY T1.CountryName HAVING count(*)  >=  3;;
SELECT DISTINCT T1.model FROM car_1_MODEL_LIST AS T1 JOIN car_1_CAR_NAMES AS T2 ON T1.model  =  T2.model JOIN car_1_CARS_DATA AS T3 ON T2.MakeId  =  T3.id WHERE T3.year  >  1980;;
SELECT avg(ranking) ,  T1.first_name FROM wta_1_players AS T1 JOIN wta_1_rankings AS T2 ON T1.player_id  =  T2.player_id GROUP BY T1.first_name;
SELECT sum(Population) ,  max(GNP) FROM world_1_country WHERE Continent  =  "Asia";
SELECT sum(SurfaceArea) FROM world_1_country WHERE Region  =  "Caribbean";
SELECT T2.name FROM network_1_Friend AS T1 JOIN network_1_Highschooler AS T2 ON T1.student_id  =  T2.id WHERE T2.grade  >  5 GROUP BY T1.student_id HAVING count(*)  >=  2;
SELECT T1.ContId ,  T1.Continent ,  count(*) FROM car_1_CONTINENTS AS T1 JOIN car_1_COUNTRIES AS T2 ON T1.ContId  =  T2.Continent GROUP BY T1.ContId;;
SELECT T1.City FROM flight_2_AIRPORTS AS T1 JOIN flight_2_FLIGHTS AS T2 ON T1.AirportCode  =  T2.DestAirport GROUP BY T1.City ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM employee_hire_evaluation_employee;
SELECT T3.Name ,  T2.Course FROM course_teach_course_arrange AS T1 JOIN course_teach_course AS T2 ON T1.Course_ID  =  T2.Course_ID JOIN course_teach_teacher AS T3 ON T1.Teacher_ID  =  T3.Teacher_ID;
SELECT T1.document_id ,  T2.document_name ,  count(*) FROM cre_Doc_Template_Mgt_Paragraphs AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.document_id  =  T2.document_id GROUP BY T1.document_id;
SELECT avg(age) FROM dog_kennels_Dogs WHERE dog_id IN ( SELECT dog_id FROM dog_kennels_Treatments );
SELECT AirportName FROM flight_2_Airports WHERE AirportCode NOT IN (SELECT SourceAirport FROM flight_2_Flights UNION SELECT DestAirport FROM flight_2_Flights);
SELECT T1.killed ,  T1.injured FROM battle_death_death AS T1 JOIN battle_death_ship AS t2 ON T1.caused_by_ship_id  =  T2.id WHERE T2.tonnage  =  't';
SELECT T1.breed_name FROM dog_kennels_Breeds AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.breed_code  =  T2.breed_code GROUP BY T1.breed_name ORDER BY count(*) DESC LIMIT 1;
SELECT avg(weight) ,  pettype FROM pets_1_pets GROUP BY pettype;
SELECT ID FROM network_1_Highschooler WHERE name  =  "Kyle";
SELECT avg(Weight) ,  YEAR FROM car_1_CARS_DATA GROUP BY YEAR;;
SELECT T1.document_id ,  T2.document_name FROM cre_Doc_Template_Mgt_Paragraphs AS T1 JOIN cre_Doc_Template_Mgt_Documents AS T2 ON T1.document_id  =  T2.document_id GROUP BY T1.document_id ORDER BY count(*) DESC LIMIT 1;
SELECT count(*) FROM cre_Doc_Template_Mgt_Documents AS T1 JOIN cre_Doc_Template_Mgt_Templates AS T2 ON T1.Template_ID  =  T2.Template_ID WHERE T2.Template_Type_Code  =  'PPT';
SELECT T1.last_name FROM dog_kennels_Owners AS T1 JOIN dog_kennels_Dogs AS T2 ON T1.owner_id  =  T2.owner_id WHERE T2.age  =  ( SELECT max(age) FROM dog_kennels_Dogs );
SELECT max(charge_amount) FROM dog_kennels_Charges;
SELECT weight FROM pets_1_pets ORDER BY pet_age LIMIT 1;
SELECT count(DISTINCT LOCATION) FROM employee_hire_evaluation_shop;
SELECT Title FROM tvshow_Cartoon ORDER BY title;
SELECT count(*) FROM voter_1_area_code_state;
SELECT DISTINCT CountryCode FROM world_1_countrylanguage WHERE LANGUAGE != "English";
SELECT name ,  Level_of_membership FROM museum_visit_visitor WHERE Level_of_membership  >  4 ORDER BY age DESC;
SELECT avg(transcript_date) FROM student_transcripts_tracking_Transcripts;
SELECT student_id FROM network_1_Friend INTERSECT SELECT liked_id FROM network_1_Likes;
SELECT avg(GNP) ,  sum(population) FROM world_1_country WHERE GovernmentForm  =  "US Territory";
select avg(horsepower) FROM car_1_cars_data where year  <  1980;;
SELECT Name FROM singer_singer WHERE Birth_Year  =  1948 OR Birth_Year  =  1949;
select other_details FROM cre_Doc_Template_Mgt_paragraphs where paragraph_text like 'korea';
SELECT count(*) FROM flight_2_FLIGHTS WHERE SourceAirport  =  "APG";
SELECT T1.name ,  T1.date FROM battle_death_battle AS T1 JOIN battle_death_ship AS T2 ON T1.id  =  T2.lost_in_battle WHERE T2.name  =  'Lettice' INTERSECT SELECT T1.name ,  T1.date FROM battle_death_battle AS T1 JOIN battle_death_ship AS T2 ON T1.id  =  T2.lost_in_battle WHERE T2.name  =  'HMS Atalanta';
SELECT count(*) FROM dog_kennels_Dogs WHERE age  <  ( SELECT avg(age) FROM dog_kennels_Dogs );
SELECT Name ,  SurfaceArea ,  IndepYear FROM world_1_country ORDER BY Population LIMIT 1;
SELECT T1.Name FROM singer_singer AS T1 JOIN singer_song AS T2 ON T1.Singer_ID  =  T2.Singer_ID GROUP BY T1.Name HAVING COUNT(*)  >  1;
SELECT name FROM network_1_Highschooler WHERE grade  =  10;
SELECT contestant_number ,  contestant_name FROM voter_1_contestants ORDER BY contestant_name DESC;
SELECT T3.Name FROM course_teach_course_arrange AS T1 JOIN course_teach_course AS T2 ON T1.Course_ID  =  T2.Course_ID JOIN course_teach_teacher AS T3 ON T1.Teacher_ID  =  T3.Teacher_ID WHERE T2.Course  =  "Math";
SELECT T1.professional_id ,  T1.cell_number FROM dog_kennels_Professionals AS T1 JOIN dog_kennels_Treatments AS T2 ON T1.professional_id  =  T2.professional_id GROUP BY T1.professional_id HAVING count(*)  >=  2;
select t1.fname FROM pets_1_student as t1 JOIN pets_1_has_pet as t2 on t1.stuid  =  t2.stuid JOIN pets_1_pets as t3 on t3.petid  =  t2.petid where t3.pettype  =  'cat' intersect select t1.fname FROM pets_1_student as t1 JOIN pets_1_has_pet as t2 on t1.stuid  =  t2.stuid JOIN pets_1_pets as t3 on t3.petid  =  t2.petid where t3.pettype  =  'dog';
SELECT Name FROM world_1_country WHERE Continent  =  "Africa"  AND population  <  (SELECT max(population) FROM world_1_country WHERE Continent  =  "Asia");
select t1.id ,  t1.maker FROM car_1_car_makers as t1 JOIN car_1_model_list as t2 on t1.id  =  t2.maker group by t1.id having count(*)  >=  2 intersect select t1.id ,  t1.maker FROM car_1_car_makers as t1 JOIN car_1_model_list as t2 on t1.id  =  t2.maker JOIN car_1_car_names as t3 on t2.model  =  t3.model group by t1.id having count(*)  >  3;;
SELECT sum(bonus) FROM employee_hire_evaluation_evaluation;
SELECT semester_name FROM student_transcripts_tracking_Semesters WHERE semester_id NOT IN( SELECT semester_id FROM student_transcripts_tracking_Student_Enrolment );
SELECT Code FROM world_1_country WHERE GovernmentForm != "Republic" EXCEPT SELECT CountryCode FROM world_1_countrylanguage WHERE LANGUAGE  =  "English";
SELECT template_id FROM cre_Doc_Template_Mgt_Templates EXCEPT SELECT template_id FROM cre_Doc_Template_Mgt_Documents;